# Generated by Django 5.0.4 on 2024-04-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quality_control", "0003_alter_featurerequest_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bugreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "Новый"),
                    ("In_progress", "В работе"),
                    ("Completed", "Завершено"),
                ],
                default="new",
                max_length=50,
            ),
        ),
    ]
