# Generated by Django 5.0.4 on 2024-04-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quality_control", "0005_alter_featurerequest_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bugreport",
            name="priority",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")], default=1
            ),
        ),
    ]
