# Generated by Django 5.0.4 on 2024-04-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "Новая"),
                    ("In_progress", "В работе"),
                    ("Completed", "Завершена"),
                ],
                default="New",
                max_length=50,
            ),
        ),
    ]
